services:
  - type: web
    name: order-app-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: order-app-ui
    runtime: static
    rootDir: ui
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://order-app-backend-ujgf.onrender.com
